[ISSUE #1709] Add test case for shenyu-admin module
apache/incubator-shenyu pull request #1710
Opened 2021-07-04 07:07 UTC by renzhuyan

// Describe your PR here; eg. Fixes #1709 

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2021-07-04 11:58 UTC, dengliming requested changes
Thanks for your contribution. I left some suggestions. Would you mind to take a look? : )

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdClientTest.java
> +        etcdClient.put(TEST_KEY, TEST_VALUE);
It also makes sense to verify what we expect. not just calling. : )
`verify(client.getKVClient(), times(1)).put(any(ByteSequence.class), any(ByteSequence.class));`

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdClientTest.java
> +        etcdClient.delete(TEST_KEY);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdClientTest.java
> +        etcdClient.deleteEtcdPathRecursive(TEST_KEY);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
> +        etcdDataDataChangedListener.onAppAuthChanged(ImmutableList.of(appAuthData), DataEventTypeEnum.DELETE);
```
verify(etcdClient, times(2)).put(any(String.class), any(String.class));
verify(etcdClient, times(1)).delete(any(String.class));
```

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
> +        etcdDataDataChangedListener.onMetaDataChanged(ImmutableList.of(metaData), DataEventTypeEnum.DELETE);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
> +        etcdDataDataChangedListener.onPluginChanged(ImmutableList.of(pluginData), DataEventTypeEnum.DELETE);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
> +        etcdDataDataChangedListener.onSelectorChanged(ImmutableList.of(selectorData), DataEventTypeEnum.DELETE);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
> +        etcdDataDataChangedListener.onRuleChanged(ImmutableList.of(ruleData), DataEventTypeEnum.DELETE);
The same as above.

2021-07-04 11:58 UTC, dengliming commented on shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListenerTest.java
> +
verify(configService, times(4)).publishConfig(any(String.class), any(String.class), any(String.class));

2021-07-04 14:31 UTC, renzhuyan commented
> Thanks for your contribution. I left some suggestions. Would you mind to take a look? : )

Thank you for your suggestions. Please look again.

2021-07-05 13:02 UTC, dengliming approved these changes

2021-07-05 13:02 UTC, merged