[type:feature] optimeze sql file for plugin-handle,shenyu-dict
apache/incubator-shenyu pull request #2466
Opened 2021-11-25 16:05 UTC by nuo-promise

// Describe your PR here; eg. Fixes #issueNo

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2021-11-26 01:05 UTC, AhahaGe commented
please change the title, with issue no

2021-11-26 03:20 UTC, yu199195 requested changes
pls wait me review

2021-11-26 03:23 UTC, nuo-promise commented
> pls wait me review

ths..

2021-11-29 06:36 UTC, yu199195 submitted a review, later dismissed

2021-11-29 08:32 UTC, yu199195 approved these changes

2021-11-29 08:32 UTC, merged